# -*- coding: utf-8 -*-
{
    "name": "Legal Case Management",
    "version": "1.0.0",
    "summary": "Manage legal cases, hearings, documents and fixed-fee invoicing (Odoo 18 Community)",
    "description": "Minimal OCA-style module to manage legal cases, hearings, attachments and simple fixed-fee invoicing. AGPL-3 licensed.",
    "author": "Generated by ChatGPT (Odoo expert)",
    "license": "AGPL-3",
    "category": "Legal",
    "depends": ["base", "mail", "account", "calendar"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/data.xml",
        "views/menus.xml",
        "views/res_partner_views.xml",
        "views/legal_case_views.xml",
        "views/legal_hearing_views.xml",
        "reports/report.xml",
        "reports/case_summary_template.xml"
    ],
    "demo": [
        "demo/demo.xml"
    ],
    "installable": True,
    "application": True,
    "auto_install": False
}
